# permissions for end users to view giteas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitea-viewer-role
rules:
- apiGroups:
  - gpte.opentlc.com
  resources:
  - giteas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gpte.opentlc.com
  resources:
  - giteas/status
  verbs:
  - get
